manifest:
  remotes:
  - name: zmkfirmware
    url-base: https://github.com/zmkfirmware
  - name: nickconway
    #Use branch smart-interrupt
    url-base: https://github.com/nickconway
  - name: caksoylar
    #Use branch caksoylar/experimental
    url-base: https://github.com/caksoylar
  - name: ulmanyar
    url-base: https://github.com/ulmanyar
  - name: petejohanson
    url-base: https://github.com/petejohanson
  projects:
  - name: zmk
    remote: petejohanson
    revision: feat/pointers-move-scroll
    import: app/west.yml
  - name: zmk-analog-input-driver
    remote: badjeff
    revision: main
  self:
    path: config
